### ISSUE TITLE
Problem with SSR

### ISSUE THREAD

**Issue by MarieCharbonneau2** [hamzahamidi/ajsf#143]
Problem with SSR : 

/var/www/docroot/node_modules/lodash-es/isEqual.js:1
import baseIsEqual from './_baseIsEqual.js';
      ^^^^^^^^^^^
SyntaxError: Unexpected identifier
at Module._compile (internal/modules/cjs/loader.js:723:23)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)
at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:70:39)
 at require (internal/modules/cjs/helpers.js:25:18)
at /var/www/docroot/node_modules/angular6-json-schema-form/bundles/angular6-json-schema-form.umd.js:2:128
at Object.<anonymous> (/var/www/docroot/node_modules/angular6-json-schema-form/bundles/angular6-json-schema-form.umd.js:5:2)

Angular version is 7

**Comment by soyuka** [comment]
Additional notes:
- lodash-es was installed
- issue is that angular SSR tries to load the code using some evaluation mode that doesn't support ES modules
- note that the client-side loaded code works without hassle
